### ISSUE TITLE
[FEAT] 초기 도메인 생성

### ISSUE THREAD

**Issue by ziiyouth** [SOPT-33th-Joint-Seminar-WEB-1/Server#1]
## 📌  Feature Issue
- 개발을 위한 도메인 생성 작업입니다.
- Book, Heart, Cart, Review

## 📝  To-do
- [x] 도서 도메인 생성
- [x] 좋아요 도메인 생성
- [x] 장바구니 도메인 생성
- [x] 리뷰 도메인 생성
